### ISSUE TITLE
Android progress

### ISSUE THREAD

**Issue by vikramarka** [neilrackett/air-chromecast-ane#2]
Is there any ETA for android version?

**Comment by neilrackett** [comment]
Now that most versions of Android include a "Cast" feature, our original use case no longer exists, so it's currently a low priority.

However, the current Android implementation, based on [cordova-chromecast](https://github.com/videostream/cordova-chromecast), _should_ be nearly complete, so if anyone has the time/inclination to help finish it, it would be highly appreciated!

Right now, the JAR compiles, but there appears to be a dependency issue that needs resolving.
